#pragma once

#define EE_HANDS

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET

#define SPLIT_USB_DETECT
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_PIN_SWAP
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1


#define OLED_DISPLAY_128X64
#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP8
#define I2C1_SCL_PIN GP9
#define OLED_DISPLAY_ADDRESS 0x3C

#define JOYSTICK_AXIS_COUNT 2
#define JOYSTICK_AXIS_RESOLUTION 12
